### ISSUE TITLE
TODO/FIXME Count 15

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-authn-token-http#9]
- [ ] TODO: support other recovery methods; only email supported presently
       Commit: (d7e1b54) Add HTTP endpoint for setting recovery information.
       File:  [lib/index.js:273](https://github.com/digitalbazaar/bedrock-authn-token-http/blob/master/lib/index.js#L273)
       Dave Longley commented 4 months ago

  - [x] FIXME: implement validation
       Commit: (d7e1b54) Add HTTP endpoint for setting recovery information.
       File:  [lib/index.js:268](https://github.com/digitalbazaar/bedrock-authn-token-http/blob/master/lib/index.js#L268)
       Dave Longley commented 4 months ago

  - [ ] const clientId = 'FIXME';
       Commit: (a8a8255) Provide client registration and account authentication method info.
       File:  [lib/index.js:259](https://github.com/digitalbazaar/bedrock-authn-token-http/blob/master/lib/index.js#L259)
       Dave Longley commented 4 months ago

  - [x] FIXME: implement validation
       Commit: (a8a8255) Provide client registration and account authentication method info.
       File:  [lib/index.js:255](https://github.com/digitalbazaar/bedrock-authn-token-http/blob/master/lib/index.js#L255)
       Dave Longley commented 4 months ago

  - [x] FIXME: implement validation
       Commit: (f1e1ac5) Add HTTP endpoint for getting account authn requirements.
       File:  [lib/index.js:242](https://github.com/digitalbazaar/bedrock-authn-token-http/blob/master/lib/index.js#L242)
       Dave Longley commented 4 months ago

  - [x] FIXME: implement validation
       Commit: (f2bc128) Add endpoint to set authentication requirements for an account.
       File:  [lib/index.js:229](https://github.com/digitalbazaar/bedrock-authn-token-http/blob/master/lib/index.js#L229)
       Dave Longley commented 4 months ago

  - [x] FIXME: implement validation
       Commit: (1108366) Start adding multifactor authentication.
       File:  [lib/index.js:186](https://github.com/digitalbazaar/bedrock-authn-token-http/blob/master/lib/index.js#L186)
       Dave Longley commented 4 months ago

  - [ ] const clientId = 'FIXME';
       Commit: (44b8a17) Add FIXME for client ID.
       File:  [lib/index.js:161](https://github.com/digitalbazaar/bedrock-authn-token-http/blob/master/lib/index.js#L161)
       Dave Longley commented 4 months ago

  - [ ] FIXME: get client ID from cookie
       Commit: (44b8a17) Add FIXME for client ID.
       File:  [lib/index.js:160](https://github.com/digitalbazaar/bedrock-authn-token-http/blob/master/lib/index.js#L160)
       Dave Longley commented 4 months ago

  - [ ] const clientId = 'FIXME';
       Commit: (44b8a17) Add FIXME for client ID.
       File:  [lib/index.js:132](https://github.com/digitalbazaar/bedrock-authn-token-http/blob/master/lib/index.js#L132)
       Dave Longley commented 4 months ago

  - [ ] FIXME: get client ID from cookie
       Commit: (44b8a17) Add FIXME for client ID.
       File:  [lib/index.js:131](https://github.com/digitalbazaar/bedrock-authn-token-http/blob/master/lib/index.js#L131)
       Dave Longley commented 4 months ago

  - [x] FIXME: implement validation
       Commit: (1108366) Start adding multifactor authentication.
       File:  [lib/index.js:94](https://github.com/digitalbazaar/bedrock-authn-token-http/blob/master/lib/index.js#L94)
       Dave Longley commented 4 months ago

  - [x] TODO: validate('services.authn.token.postToken')
       Commit: (12e303e) Add core files.
       File:  [lib/index.js:50](https://github.com/digitalbazaar/bedrock-authn-token-http/blob/master/lib/index.js#L50)
       Dave Longley commented 2 years ago

  - [x] TODO: validate({query: 'services.authn.token.postToken.query'})
       Commit: (12e303e) Add core files.
       File:  [lib/index.js:49](https://github.com/digitalbazaar/bedrock-authn-token-http/blob/master/lib/index.js#L49)
       Dave Longley commented 2 years ago

  - [ ] TODO: support `phoneNumber` in the future
       Commit: (12e303e) Add core files.
       File:  [lib/TokenStrategy.js:23](https://github.com/digitalbazaar/bedrock-authn-token-http/blob/master/lib/TokenStrategy.js#L23)
       Dave Longley commented 2 years ago

**Comment by dlongley** [comment]
Addressed by #26 / removed.
